[package]
name = "ununlucke"
version = "0.1.0"
edition = "2021"

[dependencies]
chacha20poly1305 = { version = "0.10.1", features = ["stream"] }
rand = "0.8.5"

[build-dependencies]
static_vcruntime = "2.0.0"
